### ISSUE TITLE
MAPILeak cause outlook not working

### ISSUE THREAD

**Issue by czlitony** [stephenegriffin/LeakMAPI#2]
I have written a program to test MAPILeak. In this program, I call MAPIInitialize, and search outlook contact, then exit without calling MAPIUninitialize. I write a python script to run this program repeatedly, after dozens of times, MAPIInitialize are successful and can still fetch outlook contact. But outlook 2016 itself does not work, it shows this error
> Can not display the foler. 'xxxxx.exe' exited without properly closing your Outlook data file 'C:\
> Users\xxxxx'... 'xxxxx.exe' for assistence

@stephenegriffin  Do you know the reason why outlook not working?

**Comment by stephenegriffin** [comment]
I mean - the program is called "MAPILeak" and you ran it dozens of times... Maybe don't leak MAPI?
